[ui]	
color_scheme = "dark"
background = "#282828"
text_background = "#ebdbb2"
surface = "#3c3836"
text_surface = "#ebdbb2"
primary = "#d65d0e"
text_primary = "#ebdbb2"
secondary = "#fe8019"
border = "#928374"
shadow = "#1d202180"

success = "#98971a"
text_success = "#ebdbb2"
info = "#458588"
text_info = "#ebdbb2"
warning = "#d79921"
text_warning = "#ebdbb2"
error = "#cc241d"
text_error = "#ebdbb2"

[terminal]
black = "#1d2021"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"
