[ui]
color_scheme = "dark"
background = "#303446"
text_background = "#c6d0f5"
surface = "#414550"
text_surface = "#c6d0f5"
primary = "#ca9ee6"
text_primary = "#303446"
secondary = "#ea999c"
border = "#232634"
shadow = "#21222c80"

success = "#a6d189"
text_success = "#303446"
info = "#8caaee"
text_info = "#303446"
warning = "#e5c890"
text_warning = "#303446"
error = "#e78284"
text_error = "#303446"

[terminal]
black = "#414559"
red = "#e78284"
green = "#a6d189"
yellow = "#ef9f76"
blue = "#8caaee"
magenta = "#ca9ee6"
cyan = "#85c1dc"
white = "#b5bfe2"
bright_black = "#a5adce"
bright_red = "#ea999c"
bright_green = "#81c8be"
bright_yellow = "#e5c890"
bright_blue = "#99d1db"
bright_magenta = "#f4b8e4"
bright_cyan = "#81c8be"
bright_white = "#c6d0f5"
