[ui]
color_scheme = "light"
background = "#eff1f5"
text_background = "#4c4f69"
surface = "#ccd0da"
text_surface = "#4c4f69"
primary = "#dc8a78"
text_primary = "#eff1f5"
secondary = "#8839ef"
border = "#dce0e8"
shadow = "#21222c80"

success = "#40a02b"
text_success = "#eff1f5"
info = "#1e66f5"
text_info = "#eff1f5"
warning = "#df8e1d"
text_warning = "#eff1f5"
error = "#d20f39"
text_error = "#eff1f5"

[terminal]
black = "#9ca0b0"
red = "#e64553"
green = "#179299"
yellow = "#df8e1d"
blue = "#04a5e5"
magenta = "#ea76cb"
cyan = "#209fb5"
white = "#5c5f77"
bright_black = "#6c6f85"
bright_red = "#d20f39"
bright_green = "#40a02b"
bright_yellow = "#fe640b"
bright_blue = "#1e66f5"
bright_magenta = "#7287fd"
bright_cyan = "#179299"
bright_white = "#4c4f69"
