[ui]
color_scheme = "dark"
background = "#282a36"
text_background = "#f8f8f2"
surface = "#44475a"
text_surface = "#f8f8f2"
primary = "#bd93f9"
text_primary = "#282a36"
secondary = "#50FA7B"
border = "#282a36"
shadow = "#21222cee"

info = "#6272a4"
text_info = "#f8f8f2"
warning = "#f1fa8c"
text_warning = "#282a36"
error = "#ff5555"
text_error = "#f8f8f2"

[terminal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"
bright_black = "#6272a4"
bright_red = "#ff6e6e"
bright_green = "#69ff94"
bright_yellow = "#ffffa5"
bright_blue = "#d6acff"
bright_magenta = "#ff92df"
bright_cyan = "#a4ffff"
bright_white = "#ffffff"
