[ui]
color_scheme = "dark"
background = "#282a36"
text_background = "#f8f8f2"
surface = "#44475a"
text_surface = "#f8f8f2"
primary = "#bd93f9"
text_primary = "#282a36"
border = "#747999"

info = "#6272a4"
text_info = "#f8f8f2"
warning = "#f1fa8c"
text_warning = "#282a36"
error = "#ff5555"
text_error = "#f8f8f2"

[palette]
black = "#282a36"
dark_red = "#b23a3a"
dark_green = "#39b257"
orange = "#ffb86c"
dark_blue = "#6272a4"
purple = "#bd93f9"
turquoise = "#62a3b2"
light_gray = "#ccccc7"
dark_gray = "#44475a"
bright_red = "#ff5555"
bright_green = "#50fa7b"
yellow = "#f1fa8c"
bright_blue = "#89a0e5"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"
