[ui]
color_scheme = "light"
background = "#fbf1c7"
text_background = "#3c3836"
surface = "#d5c4a1"
text_surface = "#3c3836"
primary = "#d65d0e"
text_primary = "#3c3836"
secondary = "#af3a03"
border = "#928374"
shadow = "#21222c80"

success = "#98971a"
text_success = "#3c3836"
info = "#458588"
text_info = "#3c3836"
warning = "#d79921"
text_warning = "#3c3836"
error = "#cc241d"
text_error = "#3c3836"

[terminal]
black = "#fbf1c7"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#7c6f64"
bright_black = "#928374"
bright_red = "#9d0006"
bright_green = "#79740e"
bright_yellow = "#b57614"
bright_blue = "#076678"
bright_magenta = "#8f3f71"
bright_cyan = "#427b58"
bright_white = "#3c3836"
