[book]
authors = ["Nicholas Roether"]
language = "en"
multilingual = false
src = "src"
title = "niji Documentation"
description = "Bringing comfortable theming to the tinkerer's desktop"

[output.html]
site-url = "/niji/"
git-repository-url = "https://github.com/nicholas-roether/niji/master/guide"
